# Generated by Django 2.1.4 on 2018-12-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lootlists', '0002_lootlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lootlist',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lootlist',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
