# Generated by Django 2.1.4 on 2018-12-20 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lootlists', '0003_auto_20181218_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lootlist',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='lootlist',
            name='guests',
            field=models.ManyToManyField(related_name='guest_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
